### ISSUE TITLE
Deeper integration with the Bioregistry

### ISSUE THREAD

**Issue by cthoyt** [ccb-hms/ontology-mapper#27]
Hey all, I'm working under Ben Gyori and heard about this project a the CCB seminar today. I see that you're using the Bioregistry, but maybe you're not aware that it implements a lot of the functionality for processing IRIs, CURIEs, and prefixes. It would be great to have a call and chat about how you might be able to leverage the Bioregistry package more heavily (I'm the developer!)

**Comment by paynejason** [comment]
Hi, just shot you an email.

**Comment by paynejason** [comment]
Hi Charlie,

It was great to talk to you a few weeks ago! With the newest update, we incorporated some of the easier suggestions you made in the meeting (caching returning an object and using bioregistry to fetch OWL download links), so I'm going to close out this issue. We are sure to do more in the future,  and feel free to reach out whenever!

**Comment by cthoyt** [comment]
@paynejason that's great, can you point me to some of the code that changed so I can take a look? Then we could think about other follow-ups :)
