### ISSUE TITLE
Add support for properties

### ISSUE THREAD

**Issue by nleguillarme** [ccb-hms/ontology-mapper#29]
Hi, great tool, thank you for your work !

Would it be possible to also search for property terms ?

I see in term_collector.py that you filter out PropertyClass terms:
`if not isinstance(ontology_term, PropertyClass) and ontology_term is not Thing \
                    and ontology_term is not Nothing:`

Would it be possible to provide arguments to control this behavior ?

**Comment by rsgoncalves** [comment]
Hi @nleguillarme — Thank you, we are glad to hear that!

Yes, we can certainly support search for property terms. To help us design a suitable solution, would you mind giving us a general idea of your use case? For example, are there scenarios where you would want to search for *only* properties, or would an argument to search property terms (in addition to classes) suffice?

**Comment by nleguillarme** [comment]
I would like to use ontology-mapper to annotate (ecological) datasets with concept IRIs from one or several target ontologies. My data are ecological interactions, such as (species, eats, resource), (species, parasiteOf, species)...
So I need to map interaction terms such as eats, parasiteOf to the corresponding ontological concepts, which are typically properties.

So for my own use case, I need to search both property terms and classes ; but I guess searching for only property terms could also be useful...

**Comment by rsgoncalves** [comment]
Thank you for the feedback, this is very helpful. We are working on a solution which will be included in a next release. I'll update you here once we have a pre-release implementation that could be experimented with.

**Comment by paynejason** [comment]
Hello,

We have added the functionality as requested in the newest pre-release (2.2.0). Please take a look and let us know if the functionality and documentation is sufficient. We will add it to PyPi in the next release, if we have your approval.

**Comment by nleguillarme** [comment]
Hello
I've just tested it and it seems to work as expected.
Thank you for adding this functionality.
