### ISSUE TITLE
Missing file: unstruct_terms.txt

### ISSUE THREAD

**Issue by simonmoedinger** [ccb-hms/ontology-mapper#30]
Hi :) 

would it be possible that you add the file: unstruct_terms.txt? 
It is used in the README under the "Example" section  right after the imports. That would be great, because otherwise its not possible to test the examples.

Thank you,

Simon

**Comment by paynejason** [comment]
Hi Simon, 

Sorry for the delay. The newest version includes a test/unstruct_terms.txt file with extremely basic terms. The README has been updated such that you could copy and paste an example command and it will run, so long as you are using a remote or cached ontology.

Please let us know if there is anything else, but I will mark this as closed.
