### ISSUE TITLE
map_terms returns results with score < min_score

### ISSUE THREAD

**Issue by nleguillarme** [ccb-hms/ontology-mapper#32]
Hi,

I am running the following command:
`text2term.map_terms(["binary"], "http://purl.obolibrary.org/obo/uo.owl", excl_deprecated=True, mapper=Mapper.JARO, min_score=0.95, term_type="both")`

which returns the following data frame:
```
Source Term ID Source Term Mapped Term Label Mapped Term CURIE                            Mapped Term IRI  Mapping Score
0  http://ccb.hms.harvard.edu/t2t/R5ENiT4PVmd      binary              inch        UO:0010011  http://purl.obolibrary.org/obo/UO_0010011       0.777778
1  http://ccb.hms.harvard.edu/t2t/R5ENiT4PVmd      binary              nano        UO:0000300  http://purl.obolibrary.org/obo/UO_0000300       0.722222
2  http://ccb.hms.harvard.edu/t2t/R5ENiT4PVmd      binary              pico        UO:0000302  http://purl.obolibrary.org/obo/UO_0000302       0.722222
```

I am surprised to see that the data frame contains results with a score lower than the min_score parameter. Am I doing something wrong ?

**Comment by paynejason** [comment]
Hi,

Upon inspection and testing, it appears that there is a bug for the "min_score" for any mapper that is not TF-IDF. Sorry for the inconvenience, and we will work to fix this ASAP.

**Comment by paynejason** [comment]
I have fixed the issue, please let us know if there is anything else.
